### ISSUE TITLE
Call to a member function cover() on null

### ISSUE THREAD

**Issue by mchbmn** [Andi-Lo/kirby-FacebookEvents#1]
Followed setup as directed, now getting the above Error through the Kirby debug. Ideas?

**Comment by Andi-Lo** [comment]
cover() returns the image of the related Facebook event page. It might fail if there is no image available. Can you check if this is the case?

**Comment by mchbmn** [comment]
Yes, there are certainly images for all events being called, which is why I am confused.

**Comment by Andi-Lo** [comment]
"Call to a member function cover() *on null*" would mean that you are calling `cover()` on an uninitialized object that does not has this function.

**Comment by HowieDuitt** [comment]
You're correct, I am attempting to call all previous events, and I have found some without cover images. Can you recommend a workaround? I am working with a page that has a history of 1000's of events

**Comment by mchbmn** [comment]
You were correct, I am attempting to call all previous events, and I have found some without cover images. Can you recommend a workaround? I am working with a page that has a history of 1000's of events

**Comment by Andi-Lo** [comment]
Could you provide further error details?
* Where does the code fail (line)?
* What FacebookEvent ID are you using (for reproducing)

Would be good to know if the code fails in the Plugin and the problem is a missing "not null" check on my side.

**Comment by mchbmn** [comment]
Client and I went through and edited all previous events and it worked.
