### ISSUE TITLE
Javascript 404

### ISSUE THREAD

**Issue by mchbmn** [Andi-Lo/kirby-FacebookEvents#2]
On line 4 of the example js files (and on the other included js files) you suggest` // change this according to your project name`  what is meant by "project name". Currently getting 404 errors in browser on line 14 `request.send();` 

![screen shot 2018-03-06 at 1 02 01 am](https://user-images.githubusercontent.com/26493942/37016422-16a56194-20da-11e8-835a-8885053d635a.png)

**Comment by mchbmn** [comment]
Figured that out, now getting: 

>  "Fatal error: Uncaught Error: Call to undefined function kirby() in /Users/home/Documents/WebDev/woodbine.nyc/dot-website/site/plugins/FacebookEvents/FacebookEvents.php:5 Stack trace: #0 {main} thrown in /Users/home/Documents/WebDev/woodbine.nyc/dot-website/site/plugins/FacebookEvents/FacebookEvents.php on line 5"

line 5: `kirby()->routes([
    [
      'pattern' => '(:any)/FacebookEvents.php',
      'action'  => function($uri) {
        snippet(getTemplate());
      },
      'method' => 'POST'
  	]
	]);`

I would guess this is due to the settings in the config file.

Sorry, I am not experienced with PHP at all

**Comment by mchbmn** [comment]
Why would the kirby variable become unavailable to the plugin file as specified in the kirby.php?

**Comment by Andi-Lo** [comment]
Sadly the plugin is not as straight forward to setup as I would have liked. It was my first plugin that I released and I am sorry that its a bit tricky.

I setup an example project that uses the kirby starterkit and implements this plugin. Let me suggest that you check it out and use it as a reference. As soon as you got the example project running, you should be able to setup the plugin in your own project.

Check it out here: https://github.com/Andi-Lo/FacebookEventsExample

**Comment by mchbmn** [comment]
1) In the header.php of your FacebookEventsExample you have the calls to the plugin css and js to: 
```
<?= css('assets/plugins/FacebookEvents/css/news.css') ?>
<?= js('assets/plugins/FacebookEvents/js/facebookEvents.js', true) ?>
```
neither of which exist. From what I understand Kirby CMS prevents calls to assets in plugins folder, so I copied the js and css into the main assets folder and call them from there.

2) changed `include __DIR__ . DS . 'lib' . DS . 'Event.php';` to `include __DIR__ . "/lib/Event.php";` in the  FacebookEvents.php file as it was returning DS as undefined ...

... and I am still getting the same:

> Fatal error: Uncaught Error: Call to undefined function kirby()

in addition to a javascript error:

> Uncaught TypeError: Cannot read property 'innerHTML' of null
    at XMLHttpRequest.request.onreadystatechange (facebookEvents.js:11)

**Comment by Andi-Lo** [comment]
To 1.)
  This is totally fine and thats how you make plugin assets like `css` and `js` publicly accessible. You can read more about this here: https://getkirby.com/docs/developer-guide/plugins/assets . Copying them to a main folder should not be needed.

To 2.)
  As `DS` is a kirby defined constant (in php its the `DIRECTORY_SEPARATOR` constant) it seems to me that there is something wrong with your setup. The `kirby()` function should return the global kirby object where ever you call it. https://getkirby.com/docs/cheatsheet/helpers/kirby

The javascript part seems to not find a `<div id="fb-news></div>` container in your html document, thus it's returning null. Make sure to have an element where the response can be placed into. In my example you can see that there will be a div injected via the `news.php` snippet. Inside this div the provided template will be rendered (defined in config.php)

**Comment by mchbmn** [comment]
1. understood, I am not sure why I thought they were kept private there. You may still want to edit 
```
<?= css('assets/plugins/FacebookEvents/css/news.css') ?>
<?= js('assets/plugins/FacebookEvents/js/facebookEvents.js', true) ?>
```

to 
```
<?= css('plugins/FacebookEvents/ASSETS/css/news.css') ?>
<?= js('plugins/FacebookEvents/ASSETS/js/facebookEvents.js', true) ?>
```
in your examples, no?

2) I agree, I do not know why kirby.php seems to fail as a global object. 

Currently the `<span id="fb-news"></span>` element is provided in your default news.php, called by a corresponding `<?php snippet('news') ?>` tag in the home.php. Do I need an additional container in the home.php such as your above `<div class="fb-news"></div>` in order for the js to work? I am working solely with your demo project as it was provided default, with my own page id and json credentials added in.

**Comment by mchbmn** [comment]
My config reads: 

```
c::set("facebookEventsTemplate", "site/snippets/news.php");

c::set('routes', array(
  array(
      'pattern' => '(:all)/FacebookEvents.php',
      'action'  => function($uri) {
        $news = page('home'); // a kirby page object related to the fb events
        $fbe = FacebookEvents($news);
        $events = $fbe->getFacebookEvents('XXXXXXXXXXXXXXXXX'); // your facebook page ID
        $fb_event = $fbe->getEvent($events, 0); // the first event
        snippet('sections/contentnews', array('event' => $fb_event, 'news' => $news)); // call your snippet for rendering
      },
      'method' => 'POST'
  )
));
```

**Comment by Andi-Lo** [comment]
No you don't want to add `assets` to the path. This won't work. The kirby docs state it under "Public URLs for plugin assets"

```
// As long as you store your assets in the assets folder, your assets are publicly available at the following URL: 
http://{domain}/assets/plugins/{pluginName}/{optionalSubfolder}/{filename}

// For example
http://yourdomain.com/assets/plugins/myplugin/css/myplugin.css
http://yourdomain.com/assets/plugins/myplugin/js/myplugin.js
```

and thats exactly what I'm doing there with
```
<?= css('assets/plugins/FacebookEvents/css/news.css') ?>
<?= js('assets/plugins/FacebookEvents/js/facebookEvents.js', true) ?>
```

This is how kirby internally maps those assets so it's expected behavior.

2.)
No you don't need an additional container. Just make sure it has an "id" and not a "class" (because classes are not unique and the javascript part is searching by ID)

I tried my example project by following the examples readme step by step and it works out of the box so I can not really relate to your issues :/

**Comment by Andi-Lo** [comment]
Try to delete
`c::set("facebookEventsTemplate", "site/snippets/news.php");` in your `config.php`. This might not solve the problem but I think its legacy code that is not needed anymore

**Comment by mchbmn** [comment]
Ok, I messed with the .htaccess of the Kirby CMS, and had to modify the rewrite. Also deleted the `c::set("facebookEventsTemplate", "site/snippets/news.php");` I can now see that the FacebookEvents.php is successfully calling, `kirby()` is working globally, but javascript is still returning null regardless of whether I keep your default call to the news snippet, or I eliminate the snippet and put the container in the home.php. Therefore it is being prevented from rendering.

**Comment by Andi-Lo** [comment]
If it still says that it can't call `innerHTML of null` then javascript can't find the right element in the DOM.
Are you sure that you're using a div with an ID like `<div id="fb-news"></div>` and not `<div class="fb-news"></div>` ?

**Comment by mchbmn** [comment]
Yes, for sure using `<div id="fb-news"></div>` in the news.php as provided in your example

**Comment by mchbmn** [comment]
Restarted with a fresh clone of the example. With the Rewrite modified and without my tampering (although I have no idea what I could have modified to make the innerHTML null) it likewise worked out of the box.

Thanks for bearing with me

**Comment by Andi-Lo** [comment]
no problem. Happy that it works now

**Comment by mchbmn** [comment]
Where do you recommend I place the `<?php for($i = 0; $i < count($events); $i++): ?>` for the looping? It is unclear in the readme. Is it legacy? Should I be doing something else in the `lib/Event.php` instead?

**Comment by Andi-Lo** [comment]
You can use that to print out multiple events on your page. E.g. if you would like to display the last 3 events you could do something like this:

config.php
```php
c::set('routes', array(
  array(
      'pattern' => '(:all)/FacebookEvents.php',
      'action'  => function($uri) {
        $news = page('home'); // a kirby page object related to the fb events
        $fbe = FacebookEvents($news);
        $events = $fbe->getFacebookEvents('12345678');

        for ($i = 0; $i < 3; $i++) {
          $fb_event = $fbe->getEvent($events, $i); // the first event
          snippet('sections/contentnews', array('event' => $fb_event, 'news' => $news));
        }
      },
      'method' => 'POST'
  )
));
```

Of course there are other ways of doing it but this would be one way.
