### ISSUE TITLE
Facebook API deprecations 

### ISSUE THREAD

**Issue by mchbmn** [Andi-Lo/kirby-FacebookEvents#3]
With the latest round of deprecations by Facebook, is this still method of making calls for events working for you?? 

<img width="833" alt="screen shot 2018-04-15 at 1 50 26 am" src="https://user-images.githubusercontent.com/26493942/38776516-056c5f1c-4066-11e8-8d2d-c800bccb3de5.png">

"CoverPhoto" is not one of the listed fields now banned, but it appears that these bans are having an effect where I have implemented your plugin. For example I am getting the following error:

![screen shot 2018-04-15 at 4 31 53 am](https://user-images.githubusercontent.com/26493942/38776523-31e1eada-4066-11e8-8a81-945380c9ee3c.png)

Just trying to diagnose whether it will be possible to figure out a workaround with the new regulations of Facebook API, or not.

**Comment by Andi-Lo** [comment]
I'm not really up to date with the graph API and the changes that might come. 

If you want to update the codebase to fix that issue I'm happy to receive your pull request.

**Comment by mchbmn** [comment]
Cool, I will see what I can come up with

**Comment by Andi-Lo** [comment]
With the latest GDPR regulations the event pages are not accessible anymore. The plugin is deprecated I guess.
